import { Agent, AgentContext, AgentResult, AgentConfig } from '../types/agent';
import agentService from '../services/agent';
import memoryService from '../services/memory';

export abstract class BaseAgent {
    public id: string;
    public name: string;
    public slug: string;
    public config: AgentConfig;

    constructor(agentData: Agent) {
        this.id = agentData.id;
        this.name = agentData.name;
        this.slug = agentData.slug;
        this.config = agentData.config;
    }

    /**
     * Main execution method
     */
    abstract run(context: AgentContext): Promise<AgentResult>;

    /**
     * Retrieve relevant memories for the current context
     */
    protected async getMemoryContext(query: string, limit: number = 5): Promise<string> {
        const memories = await memoryService.searchMemories({
            query,
            limit,
            threshold: 0.7
        });

        return memories.map(m => m.content).join('\n---\n');
    }

    /**
     * Store a new memory generated by the agent
     */
    protected async storeMemory(userId: string, content: string, category: 'interaction' | 'decision' | 'pattern'): Promise<void> {
        await memoryService.createMemory({
            userId,
            content,
            type: 'short_term', // Default to short term
            category,
            tags: ['agent_generated', this.slug],
            metadata: {
                agentId: this.id,
                agentSlug: this.slug
            }
        });
    }

    /**
     * Initialize the agent by ensuring it exists in the DB
     */
    static async initialize(slug: string): Promise<Agent | null> {
        return agentService.getAgentBySlug(slug);
    }
}
